name: Mirror Repo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        env:
          GITHUB_TOKEN: ${{ secrets.MIGRATE_SECRET }}
        run: |
          git clone --bare https://github.com/Rajeshcn02/CloudtoServerSync.git
          cd CloudtoServerSync.git
          git remote add github "https://Rajeshcn02:${GITHUB_TOKEN}@github.com/Rajeshcn02/Clouddata.git"
          git push --mirror github
